version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - "7474:7474"
      - "7687:7687"